// Unofficial Fortinet Terraform Provider
// Generated from templates do not manually modify
// Maintainers:
// Justin Roberts (@poroping)
package provider

import "github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema"

func providerDataSources() map[string]*schema.Resource {
	return map[string]*schema.Resource{
		"fortios_alertemail_setting": dataSourceAlertemailSetting(),

		"fortios_antivirus_heuristic": dataSourceAntivirusHeuristic(),

		"fortios_antivirus_profile":     dataSourceAntivirusProfile(),
		"fortios_antivirus_profilelist": dataSourceAntivirusProfileList(),
		"fortios_antivirus_quarantine":  dataSourceAntivirusQuarantine(),

		"fortios_antivirus_settings": dataSourceAntivirusSettings(),

		"fortios_application_custom":            dataSourceApplicationCustom(),
		"fortios_application_customlist":        dataSourceApplicationCustomList(),
		"fortios_application_group":             dataSourceApplicationGroup(),
		"fortios_application_grouplist":         dataSourceApplicationGroupList(),
		"fortios_application_list":              dataSourceApplicationList(),
		"fortios_application_listlist":          dataSourceApplicationListList(),
		"fortios_application_name":              dataSourceApplicationName(),
		"fortios_application_namelist":          dataSourceApplicationNameList(),
		"fortios_application_rule_settings":     dataSourceApplicationRuleSettings(),
		"fortios_application_rule_settingslist": dataSourceApplicationRuleSettingsList(),
		"fortios_authentication_rule":           dataSourceAuthenticationRule(),
		"fortios_authentication_rulelist":       dataSourceAuthenticationRuleList(),
		"fortios_authentication_scheme":         dataSourceAuthenticationScheme(),
		"fortios_authentication_schemelist":     dataSourceAuthenticationSchemeList(),
		"fortios_authentication_setting":        dataSourceAuthenticationSetting(),

		"fortios_certificate_ca":                         dataSourceCertificateCa(),
		"fortios_certificate_calist":                     dataSourceCertificateCaList(),
		"fortios_certificate_crl":                        dataSourceCertificateCrl(),
		"fortios_certificate_crllist":                    dataSourceCertificateCrlList(),
		"fortios_certificate_local":                      dataSourceCertificateLocal(),
		"fortios_certificate_locallist":                  dataSourceCertificateLocalList(),
		"fortios_certificate_remote":                     dataSourceCertificateRemote(),
		"fortios_certificate_remotelist":                 dataSourceCertificateRemoteList(),
		"fortios_cifs_domain_controller":                 dataSourceCifsDomainController(),
		"fortios_cifs_domain_controllerlist":             dataSourceCifsDomainControllerList(),
		"fortios_cifs_profile":                           dataSourceCifsProfile(),
		"fortios_cifs_profilelist":                       dataSourceCifsProfileList(),
		"fortios_credential_store_domain_controller":     dataSourceCredentialStoreDomainController(),
		"fortios_credential_store_domain_controllerlist": dataSourceCredentialStoreDomainControllerList(),
		"fortios_dlp_filepattern":                        dataSourceDlpFilepattern(),
		"fortios_dlp_filepatternlist":                    dataSourceDlpFilepatternList(),
		"fortios_dlp_fp_doc_source":                      dataSourceDlpFpDocSource(),
		"fortios_dlp_fp_doc_sourcelist":                  dataSourceDlpFpDocSourceList(),
		"fortios_dlp_sensitivity":                        dataSourceDlpSensitivity(),
		"fortios_dlp_sensitivitylist":                    dataSourceDlpSensitivityList(),
		"fortios_dlp_sensor":                             dataSourceDlpSensor(),
		"fortios_dlp_sensorlist":                         dataSourceDlpSensorList(),
		"fortios_dlp_settings":                           dataSourceDlpSettings(),

		"fortios_dnsfilter_domain_filter":          dataSourceDnsfilterDomainFilter(),
		"fortios_dnsfilter_domain_filterlist":      dataSourceDnsfilterDomainFilterList(),
		"fortios_dnsfilter_profile":                dataSourceDnsfilterProfile(),
		"fortios_dnsfilter_profilelist":            dataSourceDnsfilterProfileList(),
		"fortios_emailfilter_block_allow_list":     dataSourceEmailfilterBlockAllowList(),
		"fortios_emailfilter_block_allow_listlist": dataSourceEmailfilterBlockAllowListList(),
		"fortios_emailfilter_bwl":                  dataSourceEmailfilterBwl(),
		"fortios_emailfilter_bwllist":              dataSourceEmailfilterBwlList(),
		"fortios_emailfilter_bword":                dataSourceEmailfilterBword(),
		"fortios_emailfilter_bwordlist":            dataSourceEmailfilterBwordList(),
		"fortios_emailfilter_dnsbl":                dataSourceEmailfilterDnsbl(),
		"fortios_emailfilter_dnsbllist":            dataSourceEmailfilterDnsblList(),
		"fortios_emailfilter_fortishield":          dataSourceEmailfilterFortishield(),

		"fortios_emailfilter_iptrust":     dataSourceEmailfilterIptrust(),
		"fortios_emailfilter_iptrustlist": dataSourceEmailfilterIptrustList(),
		"fortios_emailfilter_mheader":     dataSourceEmailfilterMheader(),
		"fortios_emailfilter_mheaderlist": dataSourceEmailfilterMheaderList(),
		"fortios_emailfilter_options":     dataSourceEmailfilterOptions(),

		"fortios_emailfilter_profile":         dataSourceEmailfilterProfile(),
		"fortios_emailfilter_profilelist":     dataSourceEmailfilterProfileList(),
		"fortios_endpoint_control_fctems":     dataSourceEndpointControlFctems(),
		"fortios_endpoint_control_fctemslist": dataSourceEndpointControlFctemsList(),
		"fortios_endpoint_control_settings":   dataSourceEndpointControlSettings(),

		"fortios_extender_controller_extender":             dataSourceExtenderControllerExtender(),
		"fortios_extender_controller_extenderlist":         dataSourceExtenderControllerExtenderList(),
		"fortios_extender_controller_extender_profile":     dataSourceExtenderControllerExtenderProfile(),
		"fortios_extender_controller_extender_profilelist": dataSourceExtenderControllerExtenderProfileList(),
		"fortios_file_filter_profile":                      dataSourceFileFilterProfile(),
		"fortios_file_filter_profilelist":                  dataSourceFileFilterProfileList(),
		"fortios_firewallconsolidated_policy":              dataSourceFirewallConsolidatedPolicy(),
		"fortios_firewallconsolidated_policylist":          dataSourceFirewallConsolidatedPolicyList(),
		"fortios_firewallipmacbinding_setting":             dataSourceFirewallIpmacbindingSetting(),

		"fortios_firewallipmacbinding_table":        dataSourceFirewallIpmacbindingTable(),
		"fortios_firewallipmacbinding_tablelist":    dataSourceFirewallIpmacbindingTableList(),
		"fortios_firewallschedule_group":            dataSourceFirewallScheduleGroup(),
		"fortios_firewallschedule_grouplist":        dataSourceFirewallScheduleGroupList(),
		"fortios_firewallschedule_onetime":          dataSourceFirewallScheduleOnetime(),
		"fortios_firewallschedule_onetimelist":      dataSourceFirewallScheduleOnetimeList(),
		"fortios_firewallschedule_recurring":        dataSourceFirewallScheduleRecurring(),
		"fortios_firewallschedule_recurringlist":    dataSourceFirewallScheduleRecurringList(),
		"fortios_firewallservice_category":          dataSourceFirewallServiceCategory(),
		"fortios_firewallservice_categorylist":      dataSourceFirewallServiceCategoryList(),
		"fortios_firewallservice_custom":            dataSourceFirewallServiceCustom(),
		"fortios_firewallservice_customlist":        dataSourceFirewallServiceCustomList(),
		"fortios_firewallservice_group":             dataSourceFirewallServiceGroup(),
		"fortios_firewallservice_grouplist":         dataSourceFirewallServiceGroupList(),
		"fortios_firewallshaper_per_ip_shaper":      dataSourceFirewallShaperPerIpShaper(),
		"fortios_firewallshaper_per_ip_shaperlist":  dataSourceFirewallShaperPerIpShaperList(),
		"fortios_firewallshaper_traffic_shaper":     dataSourceFirewallShaperTrafficShaper(),
		"fortios_firewallshaper_traffic_shaperlist": dataSourceFirewallShaperTrafficShaperList(),
		"fortios_firewallssh_host_key":              dataSourceFirewallSshHostKey(),
		"fortios_firewallssh_host_keylist":          dataSourceFirewallSshHostKeyList(),
		"fortios_firewallssh_local_ca":              dataSourceFirewallSshLocalCa(),
		"fortios_firewallssh_local_calist":          dataSourceFirewallSshLocalCaList(),
		"fortios_firewallssh_local_key":             dataSourceFirewallSshLocalKey(),
		"fortios_firewallssh_local_keylist":         dataSourceFirewallSshLocalKeyList(),
		"fortios_firewallssh_setting":               dataSourceFirewallSshSetting(),

		"fortios_firewallssl_setting": dataSourceFirewallSslSetting(),

		"fortios_firewallwildcard_fqdn_custom":              dataSourceFirewallWildcardFqdnCustom(),
		"fortios_firewallwildcard_fqdn_customlist":          dataSourceFirewallWildcardFqdnCustomList(),
		"fortios_firewallwildcard_fqdn_group":               dataSourceFirewallWildcardFqdnGroup(),
		"fortios_firewallwildcard_fqdn_grouplist":           dataSourceFirewallWildcardFqdnGroupList(),
		"fortios_firewall_dos_policy":                       dataSourceFirewallDoSPolicy(),
		"fortios_firewall_dos_policylist":                   dataSourceFirewallDoSPolicyList(),
		"fortios_firewall_dos_policy6":                      dataSourceFirewallDoSPolicy6(),
		"fortios_firewall_dos_policy6list":                  dataSourceFirewallDoSPolicy6List(),
		"fortios_firewall_access_proxy":                     dataSourceFirewallAccessProxy(),
		"fortios_firewall_access_proxylist":                 dataSourceFirewallAccessProxyList(),
		"fortios_firewall_access_proxy6":                    dataSourceFirewallAccessProxy6(),
		"fortios_firewall_access_proxy6list":                dataSourceFirewallAccessProxy6List(),
		"fortios_firewall_access_proxy_ssh_client_cert":     dataSourceFirewallAccessProxySshClientCert(),
		"fortios_firewall_access_proxy_ssh_client_certlist": dataSourceFirewallAccessProxySshClientCertList(),
		"fortios_firewall_access_proxy_virtual_host":        dataSourceFirewallAccessProxyVirtualHost(),
		"fortios_firewall_access_proxy_virtual_hostlist":    dataSourceFirewallAccessProxyVirtualHostList(),
		"fortios_firewall_address":                          dataSourceFirewallAddress(),
		"fortios_firewall_addresslist":                      dataSourceFirewallAddressList(),
		"fortios_firewall_address6":                         dataSourceFirewallAddress6(),
		"fortios_firewall_address6list":                     dataSourceFirewallAddress6List(),
		"fortios_firewall_address6_template":                dataSourceFirewallAddress6Template(),
		"fortios_firewall_address6_templatelist":            dataSourceFirewallAddress6TemplateList(),
		"fortios_firewall_addrgrp":                          dataSourceFirewallAddrgrp(),
		"fortios_firewall_addrgrplist":                      dataSourceFirewallAddrgrpList(),
		"fortios_firewall_addrgrp6":                         dataSourceFirewallAddrgrp6(),
		"fortios_firewall_addrgrp6list":                     dataSourceFirewallAddrgrp6List(),
		"fortios_firewall_auth_portal":                      dataSourceFirewallAuthPortal(),

		"fortios_firewall_central_snat_map":              dataSourceFirewallCentralSnatMap(),
		"fortios_firewall_central_snat_maplist":          dataSourceFirewallCentralSnatMapList(),
		"fortios_firewall_city":                          dataSourceFirewallCity(),
		"fortios_firewall_citylist":                      dataSourceFirewallCityList(),
		"fortios_firewall_country":                       dataSourceFirewallCountry(),
		"fortios_firewall_countrylist":                   dataSourceFirewallCountryList(),
		"fortios_firewall_decrypted_traffic_mirror":      dataSourceFirewallDecryptedTrafficMirror(),
		"fortios_firewall_decrypted_traffic_mirrorlist":  dataSourceFirewallDecryptedTrafficMirrorList(),
		"fortios_firewall_dnstranslation":                dataSourceFirewallDnstranslation(),
		"fortios_firewall_dnstranslationlist":            dataSourceFirewallDnstranslationList(),
		"fortios_firewall_identity_based_route":          dataSourceFirewallIdentityBasedRoute(),
		"fortios_firewall_identity_based_routelist":      dataSourceFirewallIdentityBasedRouteList(),
		"fortios_firewall_interface_policy":              dataSourceFirewallInterfacePolicy(),
		"fortios_firewall_interface_policylist":          dataSourceFirewallInterfacePolicyList(),
		"fortios_firewall_interface_policy6":             dataSourceFirewallInterfacePolicy6(),
		"fortios_firewall_interface_policy6list":         dataSourceFirewallInterfacePolicy6List(),
		"fortios_firewall_internet_service":              dataSourceFirewallInternetService(),
		"fortios_firewall_internet_servicelist":          dataSourceFirewallInternetServiceList(),
		"fortios_firewall_internet_service_addition":     dataSourceFirewallInternetServiceAddition(),
		"fortios_firewall_internet_service_additionlist": dataSourceFirewallInternetServiceAdditionList(),
		"fortios_firewall_internet_service_append":       dataSourceFirewallInternetServiceAppend(),

		"fortios_firewall_internet_service_botnet":           dataSourceFirewallInternetServiceBotnet(),
		"fortios_firewall_internet_service_botnetlist":       dataSourceFirewallInternetServiceBotnetList(),
		"fortios_firewall_internet_service_custom":           dataSourceFirewallInternetServiceCustom(),
		"fortios_firewall_internet_service_customlist":       dataSourceFirewallInternetServiceCustomList(),
		"fortios_firewall_internet_service_custom_group":     dataSourceFirewallInternetServiceCustomGroup(),
		"fortios_firewall_internet_service_custom_grouplist": dataSourceFirewallInternetServiceCustomGroupList(),
		"fortios_firewall_internet_service_definition":       dataSourceFirewallInternetServiceDefinition(),
		"fortios_firewall_internet_service_definitionlist":   dataSourceFirewallInternetServiceDefinitionList(),
		"fortios_firewall_internet_service_extension":        dataSourceFirewallInternetServiceExtension(),
		"fortios_firewall_internet_service_extensionlist":    dataSourceFirewallInternetServiceExtensionList(),
		"fortios_firewall_internet_service_group":            dataSourceFirewallInternetServiceGroup(),
		"fortios_firewall_internet_service_grouplist":        dataSourceFirewallInternetServiceGroupList(),
		"fortios_firewall_internet_service_ipbl_reason":      dataSourceFirewallInternetServiceIpblReason(),
		"fortios_firewall_internet_service_ipbl_reasonlist":  dataSourceFirewallInternetServiceIpblReasonList(),
		"fortios_firewall_internet_service_ipbl_vendor":      dataSourceFirewallInternetServiceIpblVendor(),
		"fortios_firewall_internet_service_ipbl_vendorlist":  dataSourceFirewallInternetServiceIpblVendorList(),
		"fortios_firewall_internet_service_list":             dataSourceFirewallInternetServiceList(),
		"fortios_firewall_internet_service_listlist":         dataSourceFirewallInternetServiceListList(),
		"fortios_firewall_internet_service_name":             dataSourceFirewallInternetServiceName(),
		"fortios_firewall_internet_service_namelist":         dataSourceFirewallInternetServiceNameList(),
		"fortios_firewall_internet_service_owner":            dataSourceFirewallInternetServiceOwner(),
		"fortios_firewall_internet_service_ownerlist":        dataSourceFirewallInternetServiceOwnerList(),
		"fortios_firewall_internet_service_reputation":       dataSourceFirewallInternetServiceReputation(),
		"fortios_firewall_internet_service_reputationlist":   dataSourceFirewallInternetServiceReputationList(),
		"fortios_firewall_internet_service_sld":              dataSourceFirewallInternetServiceSld(),
		"fortios_firewall_internet_service_sldlist":          dataSourceFirewallInternetServiceSldList(),
		"fortios_firewall_ip_translation":                    dataSourceFirewallIpTranslation(),
		"fortios_firewall_ip_translationlist":                dataSourceFirewallIpTranslationList(),
		"fortios_firewall_ippool":                            dataSourceFirewallIppool(),
		"fortios_firewall_ippoollist":                        dataSourceFirewallIppoolList(),
		"fortios_firewall_ippool6":                           dataSourceFirewallIppool6(),
		"fortios_firewall_ippool6list":                       dataSourceFirewallIppool6List(),
		"fortios_firewall_ldb_monitor":                       dataSourceFirewallLdbMonitor(),
		"fortios_firewall_ldb_monitorlist":                   dataSourceFirewallLdbMonitorList(),
		"fortios_firewall_local_in_policy":                   dataSourceFirewallLocalInPolicy(),
		"fortios_firewall_local_in_policylist":               dataSourceFirewallLocalInPolicyList(),
		"fortios_firewall_local_in_policy6":                  dataSourceFirewallLocalInPolicy6(),
		"fortios_firewall_local_in_policy6list":              dataSourceFirewallLocalInPolicy6List(),
		"fortios_firewall_multicast_address":                 dataSourceFirewallMulticastAddress(),
		"fortios_firewall_multicast_addresslist":             dataSourceFirewallMulticastAddressList(),
		"fortios_firewall_multicast_address6":                dataSourceFirewallMulticastAddress6(),
		"fortios_firewall_multicast_address6list":            dataSourceFirewallMulticastAddress6List(),
		"fortios_firewall_multicast_policy":                  dataSourceFirewallMulticastPolicy(),
		"fortios_firewall_multicast_policylist":              dataSourceFirewallMulticastPolicyList(),
		"fortios_firewall_multicast_policy6":                 dataSourceFirewallMulticastPolicy6(),
		"fortios_firewall_multicast_policy6list":             dataSourceFirewallMulticastPolicy6List(),
		"fortios_firewall_policy":                            dataSourceFirewallPolicy(),
		"fortios_firewall_policylist":                        dataSourceFirewallPolicyList(),
		"fortios_firewall_policy46":                          dataSourceFirewallPolicy46(),
		"fortios_firewall_policy46list":                      dataSourceFirewallPolicy46List(),
		"fortios_firewall_policy6":                           dataSourceFirewallPolicy6(),
		"fortios_firewall_policy6list":                       dataSourceFirewallPolicy6List(),
		"fortios_firewall_policy64":                          dataSourceFirewallPolicy64(),
		"fortios_firewall_policy64list":                      dataSourceFirewallPolicy64List(),
		"fortios_firewall_profile_group":                     dataSourceFirewallProfileGroup(),
		"fortios_firewall_profile_grouplist":                 dataSourceFirewallProfileGroupList(),
		"fortios_firewall_profile_protocol_options":          dataSourceFirewallProfileProtocolOptions(),
		"fortios_firewall_profile_protocol_optionslist":      dataSourceFirewallProfileProtocolOptionsList(),
		"fortios_firewall_proxy_address":                     dataSourceFirewallProxyAddress(),
		"fortios_firewall_proxy_addresslist":                 dataSourceFirewallProxyAddressList(),
		"fortios_firewall_proxy_addrgrp":                     dataSourceFirewallProxyAddrgrp(),
		"fortios_firewall_proxy_addrgrplist":                 dataSourceFirewallProxyAddrgrpList(),
		"fortios_firewall_proxy_policy":                      dataSourceFirewallProxyPolicy(),
		"fortios_firewall_proxy_policylist":                  dataSourceFirewallProxyPolicyList(),
		"fortios_firewall_region":                            dataSourceFirewallRegion(),
		"fortios_firewall_regionlist":                        dataSourceFirewallRegionList(),
		"fortios_firewall_security_policy":                   dataSourceFirewallSecurityPolicy(),
		"fortios_firewall_security_policylist":               dataSourceFirewallSecurityPolicyList(),
		"fortios_firewall_shaping_policy":                    dataSourceFirewallShapingPolicy(),
		"fortios_firewall_shaping_policylist":                dataSourceFirewallShapingPolicyList(),
		"fortios_firewall_shaping_profile":                   dataSourceFirewallShapingProfile(),
		"fortios_firewall_shaping_profilelist":               dataSourceFirewallShapingProfileList(),
		"fortios_firewall_sniffer":                           dataSourceFirewallSniffer(),
		"fortios_firewall_snifferlist":                       dataSourceFirewallSnifferList(),
		"fortios_firewall_ssl_server":                        dataSourceFirewallSslServer(),
		"fortios_firewall_ssl_serverlist":                    dataSourceFirewallSslServerList(),
		"fortios_firewall_ssl_ssh_profile":                   dataSourceFirewallSslSshProfile(),
		"fortios_firewall_ssl_ssh_profilelist":               dataSourceFirewallSslSshProfileList(),
		"fortios_firewall_traffic_class":                     dataSourceFirewallTrafficClass(),
		"fortios_firewall_traffic_classlist":                 dataSourceFirewallTrafficClassList(),
		"fortios_firewall_ttl_policy":                        dataSourceFirewallTtlPolicy(),
		"fortios_firewall_ttl_policylist":                    dataSourceFirewallTtlPolicyList(),
		"fortios_firewall_vendor_mac":                        dataSourceFirewallVendorMac(),
		"fortios_firewall_vendor_maclist":                    dataSourceFirewallVendorMacList(),
		"fortios_firewall_vip":                               dataSourceFirewallVip(),
		"fortios_firewall_viplist":                           dataSourceFirewallVipList(),
		"fortios_firewall_vip46":                             dataSourceFirewallVip46(),
		"fortios_firewall_vip46list":                         dataSourceFirewallVip46List(),
		"fortios_firewall_vip6":                              dataSourceFirewallVip6(),
		"fortios_firewall_vip6list":                          dataSourceFirewallVip6List(),
		"fortios_firewall_vip64":                             dataSourceFirewallVip64(),
		"fortios_firewall_vip64list":                         dataSourceFirewallVip64List(),
		"fortios_firewall_vipgrp":                            dataSourceFirewallVipgrp(),
		"fortios_firewall_vipgrplist":                        dataSourceFirewallVipgrpList(),
		"fortios_firewall_vipgrp46":                          dataSourceFirewallVipgrp46(),
		"fortios_firewall_vipgrp46list":                      dataSourceFirewallVipgrp46List(),
		"fortios_firewall_vipgrp6":                           dataSourceFirewallVipgrp6(),
		"fortios_firewall_vipgrp6list":                       dataSourceFirewallVipgrp6List(),
		"fortios_firewall_vipgrp64":                          dataSourceFirewallVipgrp64(),
		"fortios_firewall_vipgrp64list":                      dataSourceFirewallVipgrp64List(),
		"fortios_ftp_proxy_explicit":                         dataSourceFtpProxyExplicit(),

		"fortios_icap_profile":     dataSourceIcapProfile(),
		"fortios_icap_profilelist": dataSourceIcapProfileList(),
		"fortios_icap_server":      dataSourceIcapServer(),
		"fortios_icap_serverlist":  dataSourceIcapServerList(),
		"fortios_ips_custom":       dataSourceIpsCustom(),
		"fortios_ips_customlist":   dataSourceIpsCustomList(),
		"fortios_ips_decoder":      dataSourceIpsDecoder(),
		"fortios_ips_decoderlist":  dataSourceIpsDecoderList(),
		"fortios_ips_global":       dataSourceIpsGlobal(),

		"fortios_ips_rule":              dataSourceIpsRule(),
		"fortios_ips_rulelist":          dataSourceIpsRuleList(),
		"fortios_ips_rule_settings":     dataSourceIpsRuleSettings(),
		"fortios_ips_rule_settingslist": dataSourceIpsRuleSettingsList(),
		"fortios_ips_sensor":            dataSourceIpsSensor(),
		"fortios_ips_sensorlist":        dataSourceIpsSensorList(),
		"fortios_ips_settings":          dataSourceIpsSettings(),

		"fortios_ips_view_map":     dataSourceIpsViewMap(),
		"fortios_ips_view_maplist": dataSourceIpsViewMapList(),
		"fortios_logdisk_filter":   dataSourceLogDiskFilter(),

		"fortios_logdisk_setting": dataSourceLogDiskSetting(),

		"fortios_logfortianalyzer2_filter": dataSourceLogFortianalyzer2Filter(),

		"fortios_logfortianalyzer2_override_filter": dataSourceLogFortianalyzer2OverrideFilter(),

		"fortios_logfortianalyzer2_override_setting": dataSourceLogFortianalyzer2OverrideSetting(),

		"fortios_logfortianalyzer2_setting": dataSourceLogFortianalyzer2Setting(),

		"fortios_logfortianalyzer3_filter": dataSourceLogFortianalyzer3Filter(),

		"fortios_logfortianalyzer3_override_filter": dataSourceLogFortianalyzer3OverrideFilter(),

		"fortios_logfortianalyzer3_override_setting": dataSourceLogFortianalyzer3OverrideSetting(),

		"fortios_logfortianalyzer3_setting": dataSourceLogFortianalyzer3Setting(),

		"fortios_logfortianalyzer_cloud_filter": dataSourceLogFortianalyzerCloudFilter(),

		"fortios_logfortianalyzer_cloud_override_filter": dataSourceLogFortianalyzerCloudOverrideFilter(),

		"fortios_logfortianalyzer_cloud_override_setting": dataSourceLogFortianalyzerCloudOverrideSetting(),

		"fortios_logfortianalyzer_cloud_setting": dataSourceLogFortianalyzerCloudSetting(),

		"fortios_logfortianalyzer_filter": dataSourceLogFortianalyzerFilter(),

		"fortios_logfortianalyzer_override_filter": dataSourceLogFortianalyzerOverrideFilter(),

		"fortios_logfortianalyzer_override_setting": dataSourceLogFortianalyzerOverrideSetting(),

		"fortios_logfortianalyzer_setting": dataSourceLogFortianalyzerSetting(),

		"fortios_logfortiguard_filter": dataSourceLogFortiguardFilter(),

		"fortios_logfortiguard_override_filter": dataSourceLogFortiguardOverrideFilter(),

		"fortios_logfortiguard_override_setting": dataSourceLogFortiguardOverrideSetting(),

		"fortios_logfortiguard_setting": dataSourceLogFortiguardSetting(),

		"fortios_logmemory_filter": dataSourceLogMemoryFilter(),

		"fortios_logmemory_global_setting": dataSourceLogMemoryGlobalSetting(),

		"fortios_logmemory_setting": dataSourceLogMemorySetting(),

		"fortios_lognull_device_filter": dataSourceLogNullDeviceFilter(),

		"fortios_lognull_device_setting": dataSourceLogNullDeviceSetting(),

		"fortios_logsyslogd2_filter": dataSourceLogSyslogd2Filter(),

		"fortios_logsyslogd2_override_filter": dataSourceLogSyslogd2OverrideFilter(),

		"fortios_logsyslogd2_override_setting": dataSourceLogSyslogd2OverrideSetting(),

		"fortios_logsyslogd2_setting": dataSourceLogSyslogd2Setting(),

		"fortios_logsyslogd3_filter": dataSourceLogSyslogd3Filter(),

		"fortios_logsyslogd3_override_filter": dataSourceLogSyslogd3OverrideFilter(),

		"fortios_logsyslogd3_override_setting": dataSourceLogSyslogd3OverrideSetting(),

		"fortios_logsyslogd3_setting": dataSourceLogSyslogd3Setting(),

		"fortios_logsyslogd4_filter": dataSourceLogSyslogd4Filter(),

		"fortios_logsyslogd4_override_filter": dataSourceLogSyslogd4OverrideFilter(),

		"fortios_logsyslogd4_override_setting": dataSourceLogSyslogd4OverrideSetting(),

		"fortios_logsyslogd4_setting": dataSourceLogSyslogd4Setting(),

		"fortios_logsyslogd_filter": dataSourceLogSyslogdFilter(),

		"fortios_logsyslogd_override_filter": dataSourceLogSyslogdOverrideFilter(),

		"fortios_logsyslogd_override_setting": dataSourceLogSyslogdOverrideSetting(),

		"fortios_logsyslogd_setting": dataSourceLogSyslogdSetting(),

		"fortios_logtacacsaccounting2_filter": dataSourceLogTacacsaccounting2Filter(),

		"fortios_logtacacsaccounting2_setting": dataSourceLogTacacsaccounting2Setting(),

		"fortios_logtacacsaccounting3_filter": dataSourceLogTacacsaccounting3Filter(),

		"fortios_logtacacsaccounting3_setting": dataSourceLogTacacsaccounting3Setting(),

		"fortios_logtacacsaccounting_filter": dataSourceLogTacacsaccountingFilter(),

		"fortios_logtacacsaccounting_setting": dataSourceLogTacacsaccountingSetting(),

		"fortios_logwebtrends_filter": dataSourceLogWebtrendsFilter(),

		"fortios_logwebtrends_setting": dataSourceLogWebtrendsSetting(),

		"fortios_log_custom_field":     dataSourceLogCustomField(),
		"fortios_log_custom_fieldlist": dataSourceLogCustomFieldList(),
		"fortios_log_eventfilter":      dataSourceLogEventfilter(),

		"fortios_log_gui_display": dataSourceLogGuiDisplay(),

		"fortios_log_setting": dataSourceLogSetting(),

		"fortios_log_threat_weight": dataSourceLogThreatWeight(),

		"fortios_report_chart":       dataSourceReportChart(),
		"fortios_report_chartlist":   dataSourceReportChartList(),
		"fortios_report_dataset":     dataSourceReportDataset(),
		"fortios_report_datasetlist": dataSourceReportDatasetList(),
		"fortios_report_layout":      dataSourceReportLayout(),
		"fortios_report_layoutlist":  dataSourceReportLayoutList(),
		"fortios_report_setting":     dataSourceReportSetting(),

		"fortios_report_style":            dataSourceReportStyle(),
		"fortios_report_stylelist":        dataSourceReportStyleList(),
		"fortios_report_theme":            dataSourceReportTheme(),
		"fortios_report_themelist":        dataSourceReportThemeList(),
		"fortios_router_access_list":      dataSourceRouterAccessList(),
		"fortios_router_access_listlist":  dataSourceRouterAccessListList(),
		"fortios_router_access_list6":     dataSourceRouterAccessList6(),
		"fortios_router_access_list6list": dataSourceRouterAccessList6List(),
		"fortios_router_aspath_list":      dataSourceRouterAspathList(),
		"fortios_router_aspath_listlist":  dataSourceRouterAspathListList(),
		"fortios_router_auth_path":        dataSourceRouterAuthPath(),
		"fortios_router_auth_pathlist":    dataSourceRouterAuthPathList(),
		"fortios_router_bfd":              dataSourceRouterBfd(),

		"fortios_router_bfd6": dataSourceRouterBfd6(),

		"fortios_router_bfd_neighbor":     dataSourceRouterBfdNeighbor(),
		"fortios_router_bfd_neighborlist": dataSourceRouterBfdNeighborList(),
		"fortios_router_bgp":              dataSourceRouterBgp(),

		"fortios_router_bgp_admin_distance":         dataSourceRouterBgpAdminDistance(),
		"fortios_router_bgp_admin_distancelist":     dataSourceRouterBgpAdminDistanceList(),
		"fortios_router_bgp_aggregate_address":      dataSourceRouterBgpAggregateAddress(),
		"fortios_router_bgp_aggregate_addresslist":  dataSourceRouterBgpAggregateAddressList(),
		"fortios_router_bgp_aggregate_address6":     dataSourceRouterBgpAggregateAddress6(),
		"fortios_router_bgp_aggregate_address6list": dataSourceRouterBgpAggregateAddress6List(),
		"fortios_router_bgp_neighbor":               dataSourceRouterBgpNeighbor(),
		"fortios_router_bgp_neighborlist":           dataSourceRouterBgpNeighborList(),
		"fortios_router_bgp_neighbor_group":         dataSourceRouterBgpNeighborGroup(),
		"fortios_router_bgp_neighbor_grouplist":     dataSourceRouterBgpNeighborGroupList(),
		"fortios_router_bgp_neighbor_range":         dataSourceRouterBgpNeighborRange(),
		"fortios_router_bgp_neighbor_rangelist":     dataSourceRouterBgpNeighborRangeList(),
		"fortios_router_bgp_neighbor_range6":        dataSourceRouterBgpNeighborRange6(),
		"fortios_router_bgp_neighbor_range6list":    dataSourceRouterBgpNeighborRange6List(),
		"fortios_router_bgp_network":                dataSourceRouterBgpNetwork(),
		"fortios_router_bgp_networklist":            dataSourceRouterBgpNetworkList(),
		"fortios_router_bgp_network6":               dataSourceRouterBgpNetwork6(),
		"fortios_router_bgp_network6list":           dataSourceRouterBgpNetwork6List(),
		"fortios_router_bgp_redistribute":           dataSourceRouterBgpRedistribute(),
		"fortios_router_bgp_redistributelist":       dataSourceRouterBgpRedistributeList(),
		"fortios_router_bgp_redistribute6":          dataSourceRouterBgpRedistribute6(),
		"fortios_router_bgp_redistribute6list":      dataSourceRouterBgpRedistribute6List(),
		"fortios_router_bgp_vrf_leak":               dataSourceRouterBgpVrfLeak(),
		"fortios_router_bgp_vrf_leaklist":           dataSourceRouterBgpVrfLeakList(),
		"fortios_router_bgp_vrf_leak6":              dataSourceRouterBgpVrfLeak6(),
		"fortios_router_bgp_vrf_leak6list":          dataSourceRouterBgpVrfLeak6List(),
		"fortios_router_community_list":             dataSourceRouterCommunityList(),
		"fortios_router_community_listlist":         dataSourceRouterCommunityListList(),
		"fortios_router_isis":                       dataSourceRouterIsis(),

		"fortios_router_isis_isis_interface":       dataSourceRouterIsisIsisInterface(),
		"fortios_router_isis_isis_interfacelist":   dataSourceRouterIsisIsisInterfaceList(),
		"fortios_router_isis_isis_net":             dataSourceRouterIsisIsisNet(),
		"fortios_router_isis_isis_netlist":         dataSourceRouterIsisIsisNetList(),
		"fortios_router_isis_redistribute":         dataSourceRouterIsisRedistribute(),
		"fortios_router_isis_redistributelist":     dataSourceRouterIsisRedistributeList(),
		"fortios_router_isis_redistribute6":        dataSourceRouterIsisRedistribute6(),
		"fortios_router_isis_redistribute6list":    dataSourceRouterIsisRedistribute6List(),
		"fortios_router_isis_summary_address":      dataSourceRouterIsisSummaryAddress(),
		"fortios_router_isis_summary_addresslist":  dataSourceRouterIsisSummaryAddressList(),
		"fortios_router_isis_summary_address6":     dataSourceRouterIsisSummaryAddress6(),
		"fortios_router_isis_summary_address6list": dataSourceRouterIsisSummaryAddress6List(),
		"fortios_router_key_chain":                 dataSourceRouterKeyChain(),
		"fortios_router_key_chainlist":             dataSourceRouterKeyChainList(),
		"fortios_router_multicast":                 dataSourceRouterMulticast(),

		"fortios_router_multicast6": dataSourceRouterMulticast6(),

		"fortios_router_multicast_flow":     dataSourceRouterMulticastFlow(),
		"fortios_router_multicast_flowlist": dataSourceRouterMulticastFlowList(),
		"fortios_router_ospf":               dataSourceRouterOspf(),

		"fortios_router_ospf6": dataSourceRouterOspf6(),

		"fortios_router_ospf6_area":                dataSourceRouterOspf6Area(),
		"fortios_router_ospf6_arealist":            dataSourceRouterOspf6AreaList(),
		"fortios_router_ospf6_ospf6_interface":     dataSourceRouterOspf6Ospf6Interface(),
		"fortios_router_ospf6_ospf6_interfacelist": dataSourceRouterOspf6Ospf6InterfaceList(),
		"fortios_router_ospf6_redistribute":        dataSourceRouterOspf6Redistribute(),
		"fortios_router_ospf6_redistributelist":    dataSourceRouterOspf6RedistributeList(),
		"fortios_router_ospf6_summary_address":     dataSourceRouterOspf6SummaryAddress(),
		"fortios_router_ospf6_summary_addresslist": dataSourceRouterOspf6SummaryAddressList(),
		"fortios_router_ospf_area":                 dataSourceRouterOspfArea(),
		"fortios_router_ospf_arealist":             dataSourceRouterOspfAreaList(),
		"fortios_router_ospf_distribute_list":      dataSourceRouterOspfDistributeList(),
		"fortios_router_ospf_distribute_listlist":  dataSourceRouterOspfDistributeListList(),
		"fortios_router_ospf_neighbor":             dataSourceRouterOspfNeighbor(),
		"fortios_router_ospf_neighborlist":         dataSourceRouterOspfNeighborList(),
		"fortios_router_ospf_network":              dataSourceRouterOspfNetwork(),
		"fortios_router_ospf_networklist":          dataSourceRouterOspfNetworkList(),
		"fortios_router_ospf_ospf_interface":       dataSourceRouterOspfOspfInterface(),
		"fortios_router_ospf_ospf_interfacelist":   dataSourceRouterOspfOspfInterfaceList(),
		"fortios_router_ospf_redistribute":         dataSourceRouterOspfRedistribute(),
		"fortios_router_ospf_redistributelist":     dataSourceRouterOspfRedistributeList(),
		"fortios_router_ospf_summary_address":      dataSourceRouterOspfSummaryAddress(),
		"fortios_router_ospf_summary_addresslist":  dataSourceRouterOspfSummaryAddressList(),
		"fortios_router_policy":                    dataSourceRouterPolicy(),
		"fortios_router_policylist":                dataSourceRouterPolicyList(),
		"fortios_router_policy6":                   dataSourceRouterPolicy6(),
		"fortios_router_policy6list":               dataSourceRouterPolicy6List(),
		"fortios_router_prefix_list":               dataSourceRouterPrefixList(),
		"fortios_router_prefix_listlist":           dataSourceRouterPrefixListList(),
		"fortios_router_prefix_list6":              dataSourceRouterPrefixList6(),
		"fortios_router_prefix_list6list":          dataSourceRouterPrefixList6List(),
		"fortios_router_rip":                       dataSourceRouterRip(),

		"fortios_router_rip_distance":            dataSourceRouterRipDistance(),
		"fortios_router_rip_distancelist":        dataSourceRouterRipDistanceList(),
		"fortios_router_rip_distribute_list":     dataSourceRouterRipDistributeList(),
		"fortios_router_rip_distribute_listlist": dataSourceRouterRipDistributeListList(),
		"fortios_router_rip_interface":           dataSourceRouterRipInterface(),
		"fortios_router_rip_interfacelist":       dataSourceRouterRipInterfaceList(),
		"fortios_router_rip_neighbor":            dataSourceRouterRipNeighbor(),
		"fortios_router_rip_neighborlist":        dataSourceRouterRipNeighborList(),
		"fortios_router_rip_network":             dataSourceRouterRipNetwork(),
		"fortios_router_rip_networklist":         dataSourceRouterRipNetworkList(),
		"fortios_router_rip_offset_list":         dataSourceRouterRipOffsetList(),
		"fortios_router_rip_offset_listlist":     dataSourceRouterRipOffsetListList(),
		"fortios_router_rip_redistribute":        dataSourceRouterRipRedistribute(),
		"fortios_router_rip_redistributelist":    dataSourceRouterRipRedistributeList(),
		"fortios_router_ripng":                   dataSourceRouterRipng(),

		"fortios_router_route_map":     dataSourceRouterRouteMap(),
		"fortios_router_route_maplist": dataSourceRouterRouteMapList(),
		"fortios_router_setting":       dataSourceRouterSetting(),

		"fortios_router_static":                        dataSourceRouterStatic(),
		"fortios_router_staticlist":                    dataSourceRouterStaticList(),
		"fortios_router_static6":                       dataSourceRouterStatic6(),
		"fortios_router_static6list":                   dataSourceRouterStatic6List(),
		"fortios_sctp_filter_profile":                  dataSourceSctpFilterProfile(),
		"fortios_sctp_filter_profilelist":              dataSourceSctpFilterProfileList(),
		"fortios_ssh_filter_profile":                   dataSourceSshFilterProfile(),
		"fortios_ssh_filter_profilelist":               dataSourceSshFilterProfileList(),
		"fortios_switch_controllerauto_config_default": dataSourceSwitchControllerAutoConfigDefault(),

		"fortios_switch_controllerinitial_config_template":     dataSourceSwitchControllerInitialConfigTemplate(),
		"fortios_switch_controllerinitial_config_templatelist": dataSourceSwitchControllerInitialConfigTemplateList(),
		"fortios_switch_controllerinitial_config_vlans":        dataSourceSwitchControllerInitialConfigVlans(),

		"fortios_switch_controllersecurity_policy_802_1x":     dataSourceSwitchControllerSecurityPolicy8021X(),
		"fortios_switch_controllersecurity_policy_802_1xlist": dataSourceSwitchControllerSecurityPolicy8021XList(),
		"fortios_switch_controller_dynamic_port_policy":       dataSourceSwitchControllerDynamicPortPolicy(),
		"fortios_switch_controller_dynamic_port_policylist":   dataSourceSwitchControllerDynamicPortPolicyList(),
		"fortios_switch_controller_fortilink_settings":        dataSourceSwitchControllerFortilinkSettings(),
		"fortios_switch_controller_fortilink_settingslist":    dataSourceSwitchControllerFortilinkSettingsList(),
		"fortios_switch_controller_global":                    dataSourceSwitchControllerGlobal(),

		"fortios_switch_controller_lldp_profile":     dataSourceSwitchControllerLldpProfile(),
		"fortios_switch_controller_lldp_profilelist": dataSourceSwitchControllerLldpProfileList(),
		"fortios_switch_controller_lldp_settings":    dataSourceSwitchControllerLldpSettings(),

		"fortios_switch_controller_location":           dataSourceSwitchControllerLocation(),
		"fortios_switch_controller_locationlist":       dataSourceSwitchControllerLocationList(),
		"fortios_switch_controller_mac_policy":         dataSourceSwitchControllerMacPolicy(),
		"fortios_switch_controller_mac_policylist":     dataSourceSwitchControllerMacPolicyList(),
		"fortios_switch_controller_managed_switch":     dataSourceSwitchControllerManagedSwitch(),
		"fortios_switch_controller_managed_switchlist": dataSourceSwitchControllerManagedSwitchList(),
		"fortios_switch_controller_nac_device":         dataSourceSwitchControllerNacDevice(),
		"fortios_switch_controller_nac_devicelist":     dataSourceSwitchControllerNacDeviceList(),
		"fortios_switch_controller_nac_settings":       dataSourceSwitchControllerNacSettings(),
		"fortios_switch_controller_nac_settingslist":   dataSourceSwitchControllerNacSettingsList(),
		"fortios_switch_controller_port_policy":        dataSourceSwitchControllerPortPolicy(),
		"fortios_switch_controller_port_policylist":    dataSourceSwitchControllerPortPolicyList(),
		"fortios_switch_controller_snmp_community":     dataSourceSwitchControllerSnmpCommunity(),
		"fortios_switch_controller_snmp_communitylist": dataSourceSwitchControllerSnmpCommunityList(),
		"fortios_switch_controller_stp_instance":       dataSourceSwitchControllerStpInstance(),
		"fortios_switch_controller_stp_instancelist":   dataSourceSwitchControllerStpInstanceList(),
		"fortios_switch_controller_stp_settings":       dataSourceSwitchControllerStpSettings(),

		"fortios_switch_controller_switch_group":     dataSourceSwitchControllerSwitchGroup(),
		"fortios_switch_controller_switch_grouplist": dataSourceSwitchControllerSwitchGroupList(),
		"fortios_switch_controller_system":           dataSourceSwitchControllerSystem(),

		"fortios_switch_controller_vlan_policy":     dataSourceSwitchControllerVlanPolicy(),
		"fortios_switch_controller_vlan_policylist": dataSourceSwitchControllerVlanPolicyList(),
		"fortios_system3g_modem_custom":             dataSourceSystem3gModemCustom(),
		"fortios_system3g_modem_customlist":         dataSourceSystem3gModemCustomList(),
		"fortios_systemautoupdate_push_update":      dataSourceSystemAutoupdatePushUpdate(),

		"fortios_systemautoupdate_schedule": dataSourceSystemAutoupdateSchedule(),

		"fortios_systemautoupdate_tunneling": dataSourceSystemAutoupdateTunneling(),

		"fortios_systemdhcp6_server":                           dataSourceSystemDhcp6Server(),
		"fortios_systemdhcp6_serverlist":                       dataSourceSystemDhcp6ServerList(),
		"fortios_systemdhcp_server":                            dataSourceSystemDhcpServer(),
		"fortios_systemdhcp_serverlist":                        dataSourceSystemDhcpServerList(),
		"fortios_systemlldp_network_policy":                    dataSourceSystemLldpNetworkPolicy(),
		"fortios_systemlldp_network_policylist":                dataSourceSystemLldpNetworkPolicyList(),
		"fortios_systemreplacemsg_admin":                       dataSourceSystemReplacemsgAdmin(),
		"fortios_systemreplacemsg_adminlist":                   dataSourceSystemReplacemsgAdminList(),
		"fortios_systemreplacemsg_alertmail":                   dataSourceSystemReplacemsgAlertmail(),
		"fortios_systemreplacemsg_alertmaillist":               dataSourceSystemReplacemsgAlertmailList(),
		"fortios_systemreplacemsg_auth":                        dataSourceSystemReplacemsgAuth(),
		"fortios_systemreplacemsg_authlist":                    dataSourceSystemReplacemsgAuthList(),
		"fortios_systemreplacemsg_automation":                  dataSourceSystemReplacemsgAutomation(),
		"fortios_systemreplacemsg_automationlist":              dataSourceSystemReplacemsgAutomationList(),
		"fortios_systemreplacemsg_device_detection_portal":     dataSourceSystemReplacemsgDeviceDetectionPortal(),
		"fortios_systemreplacemsg_device_detection_portallist": dataSourceSystemReplacemsgDeviceDetectionPortalList(),
		"fortios_systemreplacemsg_fortiguard_wf":               dataSourceSystemReplacemsgFortiguardWf(),
		"fortios_systemreplacemsg_fortiguard_wflist":           dataSourceSystemReplacemsgFortiguardWfList(),
		"fortios_systemreplacemsg_ftp":                         dataSourceSystemReplacemsgFtp(),
		"fortios_systemreplacemsg_ftplist":                     dataSourceSystemReplacemsgFtpList(),
		"fortios_systemreplacemsg_http":                        dataSourceSystemReplacemsgHttp(),
		"fortios_systemreplacemsg_httplist":                    dataSourceSystemReplacemsgHttpList(),
		"fortios_systemreplacemsg_icap":                        dataSourceSystemReplacemsgIcap(),
		"fortios_systemreplacemsg_icaplist":                    dataSourceSystemReplacemsgIcapList(),
		"fortios_systemreplacemsg_mail":                        dataSourceSystemReplacemsgMail(),
		"fortios_systemreplacemsg_maillist":                    dataSourceSystemReplacemsgMailList(),
		"fortios_systemreplacemsg_nac_quar":                    dataSourceSystemReplacemsgNacQuar(),
		"fortios_systemreplacemsg_nac_quarlist":                dataSourceSystemReplacemsgNacQuarList(),
		"fortios_systemreplacemsg_nntp":                        dataSourceSystemReplacemsgNntp(),
		"fortios_systemreplacemsg_nntplist":                    dataSourceSystemReplacemsgNntpList(),
		"fortios_systemreplacemsg_spam":                        dataSourceSystemReplacemsgSpam(),
		"fortios_systemreplacemsg_spamlist":                    dataSourceSystemReplacemsgSpamList(),
		"fortios_systemreplacemsg_sslvpn":                      dataSourceSystemReplacemsgSslvpn(),
		"fortios_systemreplacemsg_sslvpnlist":                  dataSourceSystemReplacemsgSslvpnList(),
		"fortios_systemreplacemsg_traffic_quota":               dataSourceSystemReplacemsgTrafficQuota(),
		"fortios_systemreplacemsg_traffic_quotalist":           dataSourceSystemReplacemsgTrafficQuotaList(),
		"fortios_systemreplacemsg_utm":                         dataSourceSystemReplacemsgUtm(),
		"fortios_systemreplacemsg_utmlist":                     dataSourceSystemReplacemsgUtmList(),
		"fortios_systemreplacemsg_webproxy":                    dataSourceSystemReplacemsgWebproxy(),
		"fortios_systemreplacemsg_webproxylist":                dataSourceSystemReplacemsgWebproxyList(),
		"fortios_systemsnmp_community":                         dataSourceSystemSnmpCommunity(),
		"fortios_systemsnmp_communitylist":                     dataSourceSystemSnmpCommunityList(),
		"fortios_systemsnmp_sysinfo":                           dataSourceSystemSnmpSysinfo(),

		"fortios_systemsnmp_user":       dataSourceSystemSnmpUser(),
		"fortios_systemsnmp_userlist":   dataSourceSystemSnmpUserList(),
		"fortios_system_accprofile":     dataSourceSystemAccprofile(),
		"fortios_system_accprofilelist": dataSourceSystemAccprofileList(),
		"fortios_system_acme":           dataSourceSystemAcme(),

		"fortios_system_admin":     dataSourceSystemAdmin(),
		"fortios_system_adminlist": dataSourceSystemAdminList(),
		"fortios_system_alarm":     dataSourceSystemAlarm(),

		"fortios_system_api_user":      dataSourceSystemApiUser(),
		"fortios_system_api_userlist":  dataSourceSystemApiUserList(),
		"fortios_system_arp_table":     dataSourceSystemArpTable(),
		"fortios_system_arp_tablelist": dataSourceSystemArpTableList(),
		"fortios_system_auto_install":  dataSourceSystemAutoInstall(),

		"fortios_system_auto_script":                dataSourceSystemAutoScript(),
		"fortios_system_auto_scriptlist":            dataSourceSystemAutoScriptList(),
		"fortios_system_automation_action":          dataSourceSystemAutomationAction(),
		"fortios_system_automation_actionlist":      dataSourceSystemAutomationActionList(),
		"fortios_system_automation_destination":     dataSourceSystemAutomationDestination(),
		"fortios_system_automation_destinationlist": dataSourceSystemAutomationDestinationList(),
		"fortios_system_automation_stitch":          dataSourceSystemAutomationStitch(),
		"fortios_system_automation_stitchlist":      dataSourceSystemAutomationStitchList(),
		"fortios_system_automation_trigger":         dataSourceSystemAutomationTrigger(),
		"fortios_system_automation_triggerlist":     dataSourceSystemAutomationTriggerList(),
		"fortios_system_central_management":         dataSourceSystemCentralManagement(),

		"fortios_system_cluster_sync":     dataSourceSystemClusterSync(),
		"fortios_system_cluster_synclist": dataSourceSystemClusterSyncList(),
		"fortios_system_console":          dataSourceSystemConsole(),

		"fortios_system_csf": dataSourceSystemCsf(),

		"fortios_system_custom_language":     dataSourceSystemCustomLanguage(),
		"fortios_system_custom_languagelist": dataSourceSystemCustomLanguageList(),
		"fortios_system_ddns":                dataSourceSystemDdns(),
		"fortios_system_ddnslist":            dataSourceSystemDdnsList(),
		"fortios_system_dedicated_mgmt":      dataSourceSystemDedicatedMgmt(),

		"fortios_system_dns": dataSourceSystemDns(),

		"fortios_system_dns64": dataSourceSystemDns64(),

		"fortios_system_dns_database":            dataSourceSystemDnsDatabase(),
		"fortios_system_dns_databaselist":        dataSourceSystemDnsDatabaseList(),
		"fortios_system_dns_server":              dataSourceSystemDnsServer(),
		"fortios_system_dns_serverlist":          dataSourceSystemDnsServerList(),
		"fortios_system_dscp_based_priority":     dataSourceSystemDscpBasedPriority(),
		"fortios_system_dscp_based_prioritylist": dataSourceSystemDscpBasedPriorityList(),
		"fortios_system_email_server":            dataSourceSystemEmailServer(),

		"fortios_system_external_resource":     dataSourceSystemExternalResource(),
		"fortios_system_external_resourcelist": dataSourceSystemExternalResourceList(),
		"fortios_system_federated_upgrade":     dataSourceSystemFederatedUpgrade(),

		"fortios_system_fips_cc": dataSourceSystemFipsCc(),

		"fortios_system_fortiai": dataSourceSystemFortiai(),

		"fortios_system_fortiguard": dataSourceSystemFortiguard(),

		"fortios_system_fortimanager": dataSourceSystemFortimanager(),

		"fortios_system_fortisandbox": dataSourceSystemFortisandbox(),

		"fortios_system_fsso_polling": dataSourceSystemFssoPolling(),

		"fortios_system_ftm_push": dataSourceSystemFtmPush(),

		"fortios_system_geneve":             dataSourceSystemGeneve(),
		"fortios_system_genevelist":         dataSourceSystemGeneveList(),
		"fortios_system_geoip_country":      dataSourceSystemGeoipCountry(),
		"fortios_system_geoip_countrylist":  dataSourceSystemGeoipCountryList(),
		"fortios_system_geoip_override":     dataSourceSystemGeoipOverride(),
		"fortios_system_geoip_overridelist": dataSourceSystemGeoipOverrideList(),
		"fortios_system_global":             dataSourceSystemGlobal(),

		"fortios_system_gre_tunnel":     dataSourceSystemGreTunnel(),
		"fortios_system_gre_tunnellist": dataSourceSystemGreTunnelList(),
		"fortios_system_ha":             dataSourceSystemHa(),

		"fortios_system_ha_monitor": dataSourceSystemHaMonitor(),

		"fortios_system_ike": dataSourceSystemIke(),

		"fortios_system_interface":     dataSourceSystemInterface(),
		"fortios_system_interfacelist": dataSourceSystemInterfaceList(),
		"fortios_system_ipam":          dataSourceSystemIpam(),

		"fortios_system_ipip_tunnel":     dataSourceSystemIpipTunnel(),
		"fortios_system_ipip_tunnellist": dataSourceSystemIpipTunnelList(),
		"fortios_system_ips":             dataSourceSystemIps(),

		"fortios_system_ips_urlfilter_dns":       dataSourceSystemIpsUrlfilterDns(),
		"fortios_system_ips_urlfilter_dnslist":   dataSourceSystemIpsUrlfilterDnsList(),
		"fortios_system_ips_urlfilter_dns6":      dataSourceSystemIpsUrlfilterDns6(),
		"fortios_system_ips_urlfilter_dns6list":  dataSourceSystemIpsUrlfilterDns6List(),
		"fortios_system_ipsec_aggregate":         dataSourceSystemIpsecAggregate(),
		"fortios_system_ipsec_aggregatelist":     dataSourceSystemIpsecAggregateList(),
		"fortios_system_ipv6_neighbor_cache":     dataSourceSystemIpv6NeighborCache(),
		"fortios_system_ipv6_neighbor_cachelist": dataSourceSystemIpv6NeighborCacheList(),
		"fortios_system_ipv6_tunnel":             dataSourceSystemIpv6Tunnel(),
		"fortios_system_ipv6_tunnellist":         dataSourceSystemIpv6TunnelList(),
		"fortios_system_link_monitor":            dataSourceSystemLinkMonitor(),
		"fortios_system_link_monitorlist":        dataSourceSystemLinkMonitorList(),
		"fortios_system_lte_modem":               dataSourceSystemLteModem(),

		"fortios_system_mac_address_table":     dataSourceSystemMacAddressTable(),
		"fortios_system_mac_address_tablelist": dataSourceSystemMacAddressTableList(),
		"fortios_system_mobile_tunnel":         dataSourceSystemMobileTunnel(),
		"fortios_system_mobile_tunnellist":     dataSourceSystemMobileTunnelList(),
		"fortios_system_modem":                 dataSourceSystemModem(),

		"fortios_system_nat64": dataSourceSystemNat64(),

		"fortios_system_nd_proxy": dataSourceSystemNdProxy(),

		"fortios_system_netflow": dataSourceSystemNetflow(),

		"fortios_system_network_visibility": dataSourceSystemNetworkVisibility(),

		"fortios_system_npu": dataSourceSystemNpu(),

		"fortios_system_ntp": dataSourceSystemNtp(),

		"fortios_system_object_tagging":     dataSourceSystemObjectTagging(),
		"fortios_system_object_tagginglist": dataSourceSystemObjectTaggingList(),
		"fortios_system_password_policy":    dataSourceSystemPasswordPolicy(),

		"fortios_system_password_policy_guest_admin": dataSourceSystemPasswordPolicyGuestAdmin(),

		"fortios_system_physical_switch":     dataSourceSystemPhysicalSwitch(),
		"fortios_system_physical_switchlist": dataSourceSystemPhysicalSwitchList(),
		"fortios_system_pppoe_interface":     dataSourceSystemPppoeInterface(),
		"fortios_system_pppoe_interfacelist": dataSourceSystemPppoeInterfaceList(),
		"fortios_system_probe_response":      dataSourceSystemProbeResponse(),

		"fortios_system_proxy_arp":     dataSourceSystemProxyArp(),
		"fortios_system_proxy_arplist": dataSourceSystemProxyArpList(),
		"fortios_system_ptp":           dataSourceSystemPtp(),

		"fortios_system_replacemsg_group":     dataSourceSystemReplacemsgGroup(),
		"fortios_system_replacemsg_grouplist": dataSourceSystemReplacemsgGroupList(),
		"fortios_system_replacemsg_image":     dataSourceSystemReplacemsgImage(),
		"fortios_system_replacemsg_imagelist": dataSourceSystemReplacemsgImageList(),
		"fortios_system_resource_limits":      dataSourceSystemResourceLimits(),

		"fortios_system_saml": dataSourceSystemSaml(),

		"fortios_system_sdn_connector":     dataSourceSystemSdnConnector(),
		"fortios_system_sdn_connectorlist": dataSourceSystemSdnConnectorList(),
		"fortios_system_sdwan":             dataSourceSystemSdwan(),

		"fortios_system_sdwan_duplication":      dataSourceSystemSdwanDuplication(),
		"fortios_system_sdwan_duplicationlist":  dataSourceSystemSdwanDuplicationList(),
		"fortios_system_sdwan_health_check":     dataSourceSystemSdwanHealthCheck(),
		"fortios_system_sdwan_health_checklist": dataSourceSystemSdwanHealthCheckList(),
		"fortios_system_sdwan_members":          dataSourceSystemSdwanMembers(),
		"fortios_system_sdwan_memberslist":      dataSourceSystemSdwanMembersList(),
		"fortios_system_sdwan_neighbor":         dataSourceSystemSdwanNeighbor(),
		"fortios_system_sdwan_neighborlist":     dataSourceSystemSdwanNeighborList(),
		"fortios_system_sdwan_service":          dataSourceSystemSdwanService(),
		"fortios_system_sdwan_servicelist":      dataSourceSystemSdwanServiceList(),
		"fortios_system_sdwan_zone":             dataSourceSystemSdwanZone(),
		"fortios_system_sdwan_zonelist":         dataSourceSystemSdwanZoneList(),
		"fortios_system_session_helper":         dataSourceSystemSessionHelper(),
		"fortios_system_session_helperlist":     dataSourceSystemSessionHelperList(),
		"fortios_system_session_ttl":            dataSourceSystemSessionTtl(),

		"fortios_system_settings": dataSourceSystemSettings(),

		"fortios_system_sflow": dataSourceSystemSflow(),

		"fortios_system_sit_tunnel":               dataSourceSystemSitTunnel(),
		"fortios_system_sit_tunnellist":           dataSourceSystemSitTunnelList(),
		"fortios_system_sms_server":               dataSourceSystemSmsServer(),
		"fortios_system_sms_serverlist":           dataSourceSystemSmsServerList(),
		"fortios_system_speed_test_schedule":      dataSourceSystemSpeedTestSchedule(),
		"fortios_system_speed_test_schedulelist":  dataSourceSystemSpeedTestScheduleList(),
		"fortios_system_speed_test_server":        dataSourceSystemSpeedTestServer(),
		"fortios_system_speed_test_serverlist":    dataSourceSystemSpeedTestServerList(),
		"fortios_system_sso_admin":                dataSourceSystemSsoAdmin(),
		"fortios_system_sso_adminlist":            dataSourceSystemSsoAdminList(),
		"fortios_system_sso_forticloud_admin":     dataSourceSystemSsoForticloudAdmin(),
		"fortios_system_sso_forticloud_adminlist": dataSourceSystemSsoForticloudAdminList(),
		"fortios_system_standalone_cluster":       dataSourceSystemStandaloneCluster(),

		"fortios_system_storage":     dataSourceSystemStorage(),
		"fortios_system_storagelist": dataSourceSystemStorageList(),
		"fortios_system_stp":         dataSourceSystemStp(),

		"fortios_system_switch_interface":       dataSourceSystemSwitchInterface(),
		"fortios_system_switch_interfacelist":   dataSourceSystemSwitchInterfaceList(),
		"fortios_system_tos_based_priority":     dataSourceSystemTosBasedPriority(),
		"fortios_system_tos_based_prioritylist": dataSourceSystemTosBasedPriorityList(),
		"fortios_system_vdom":                   dataSourceSystemVdom(),
		"fortios_system_vdomlist":               dataSourceSystemVdomList(),
		"fortios_system_vdom_dns":               dataSourceSystemVdomDns(),

		"fortios_system_vdom_exception":     dataSourceSystemVdomException(),
		"fortios_system_vdom_exceptionlist": dataSourceSystemVdomExceptionList(),
		"fortios_system_vdom_link":          dataSourceSystemVdomLink(),
		"fortios_system_vdom_linklist":      dataSourceSystemVdomLinkList(),
		"fortios_system_vdom_netflow":       dataSourceSystemVdomNetflow(),

		"fortios_system_vdom_property":          dataSourceSystemVdomProperty(),
		"fortios_system_vdom_propertylist":      dataSourceSystemVdomPropertyList(),
		"fortios_system_vdom_radius_server":     dataSourceSystemVdomRadiusServer(),
		"fortios_system_vdom_radius_serverlist": dataSourceSystemVdomRadiusServerList(),
		"fortios_system_vdom_sflow":             dataSourceSystemVdomSflow(),

		"fortios_system_virtual_switch":     dataSourceSystemVirtualSwitch(),
		"fortios_system_virtual_switchlist": dataSourceSystemVirtualSwitchList(),
		"fortios_system_virtual_wan_link":   dataSourceSystemVirtualWanLink(),

		"fortios_system_virtual_wire_pair":     dataSourceSystemVirtualWirePair(),
		"fortios_system_virtual_wire_pairlist": dataSourceSystemVirtualWirePairList(),
		"fortios_system_vne_tunnel":            dataSourceSystemVneTunnel(),

		"fortios_system_vxlan":               dataSourceSystemVxlan(),
		"fortios_system_vxlanlist":           dataSourceSystemVxlanList(),
		"fortios_system_wccp":                dataSourceSystemWccp(),
		"fortios_system_wccplist":            dataSourceSystemWccpList(),
		"fortios_system_zone":                dataSourceSystemZone(),
		"fortios_system_zonelist":            dataSourceSystemZoneList(),
		"fortios_user_adgrp":                 dataSourceUserAdgrp(),
		"fortios_user_adgrplist":             dataSourceUserAdgrpList(),
		"fortios_user_certificate":           dataSourceUserCertificate(),
		"fortios_user_certificatelist":       dataSourceUserCertificateList(),
		"fortios_user_domain_controller":     dataSourceUserDomainController(),
		"fortios_user_domain_controllerlist": dataSourceUserDomainControllerList(),
		"fortios_user_exchange":              dataSourceUserExchange(),
		"fortios_user_exchangelist":          dataSourceUserExchangeList(),
		"fortios_user_fortitoken":            dataSourceUserFortitoken(),
		"fortios_user_fortitokenlist":        dataSourceUserFortitokenList(),
		"fortios_user_fsso":                  dataSourceUserFsso(),
		"fortios_user_fssolist":              dataSourceUserFssoList(),
		"fortios_user_fsso_polling":          dataSourceUserFssoPolling(),
		"fortios_user_fsso_pollinglist":      dataSourceUserFssoPollingList(),
		"fortios_user_group":                 dataSourceUserGroup(),
		"fortios_user_grouplist":             dataSourceUserGroupList(),
		"fortios_user_krb_keytab":            dataSourceUserKrbKeytab(),
		"fortios_user_krb_keytablist":        dataSourceUserKrbKeytabList(),
		"fortios_user_ldap":                  dataSourceUserLdap(),
		"fortios_user_ldaplist":              dataSourceUserLdapList(),
		"fortios_user_local":                 dataSourceUserLocal(),
		"fortios_user_locallist":             dataSourceUserLocalList(),
		"fortios_user_nac_policy":            dataSourceUserNacPolicy(),
		"fortios_user_nac_policylist":        dataSourceUserNacPolicyList(),
		"fortios_user_password_policy":       dataSourceUserPasswordPolicy(),
		"fortios_user_password_policylist":   dataSourceUserPasswordPolicyList(),
		"fortios_user_peer":                  dataSourceUserPeer(),
		"fortios_user_peerlist":              dataSourceUserPeerList(),
		"fortios_user_peergrp":               dataSourceUserPeergrp(),
		"fortios_user_peergrplist":           dataSourceUserPeergrpList(),
		"fortios_user_pop3":                  dataSourceUserPop3(),
		"fortios_user_pop3list":              dataSourceUserPop3List(),
		"fortios_user_quarantine":            dataSourceUserQuarantine(),

		"fortios_user_radius":                   dataSourceUserRadius(),
		"fortios_user_radiuslist":               dataSourceUserRadiusList(),
		"fortios_user_saml":                     dataSourceUserSaml(),
		"fortios_user_samllist":                 dataSourceUserSamlList(),
		"fortios_user_security_exempt_list":     dataSourceUserSecurityExemptList(),
		"fortios_user_security_exempt_listlist": dataSourceUserSecurityExemptListList(),
		"fortios_user_setting":                  dataSourceUserSetting(),

		"fortios_user_tacacs":                            dataSourceUserTacacs(),
		"fortios_user_tacacslist":                        dataSourceUserTacacsList(),
		"fortios_videofilter_profile":                    dataSourceVideofilterProfile(),
		"fortios_videofilter_profilelist":                dataSourceVideofilterProfileList(),
		"fortios_videofilter_youtube_channel_filter":     dataSourceVideofilterYoutubeChannelFilter(),
		"fortios_videofilter_youtube_channel_filterlist": dataSourceVideofilterYoutubeChannelFilterList(),
		"fortios_videofilter_youtube_key":                dataSourceVideofilterYoutubeKey(),
		"fortios_videofilter_youtube_keylist":            dataSourceVideofilterYoutubeKeyList(),
		"fortios_voip_profile":                           dataSourceVoipProfile(),
		"fortios_voip_profilelist":                       dataSourceVoipProfileList(),
		"fortios_vpncertificate_ca":                      dataSourceVpnCertificateCa(),
		"fortios_vpncertificate_calist":                  dataSourceVpnCertificateCaList(),
		"fortios_vpncertificate_crl":                     dataSourceVpnCertificateCrl(),
		"fortios_vpncertificate_crllist":                 dataSourceVpnCertificateCrlList(),
		"fortios_vpncertificate_local":                   dataSourceVpnCertificateLocal(),
		"fortios_vpncertificate_locallist":               dataSourceVpnCertificateLocalList(),
		"fortios_vpncertificate_ocsp_server":             dataSourceVpnCertificateOcspServer(),
		"fortios_vpncertificate_ocsp_serverlist":         dataSourceVpnCertificateOcspServerList(),
		"fortios_vpncertificate_remote":                  dataSourceVpnCertificateRemote(),
		"fortios_vpncertificate_remotelist":              dataSourceVpnCertificateRemoteList(),
		"fortios_vpncertificate_setting":                 dataSourceVpnCertificateSetting(),

		"fortios_vpnipsec_concentrator":             dataSourceVpnIpsecConcentrator(),
		"fortios_vpnipsec_concentratorlist":         dataSourceVpnIpsecConcentratorList(),
		"fortios_vpnipsec_fec":                      dataSourceVpnIpsecFec(),
		"fortios_vpnipsec_feclist":                  dataSourceVpnIpsecFecList(),
		"fortios_vpnipsec_forticlient":              dataSourceVpnIpsecForticlient(),
		"fortios_vpnipsec_forticlientlist":          dataSourceVpnIpsecForticlientList(),
		"fortios_vpnipsec_manualkey":                dataSourceVpnIpsecManualkey(),
		"fortios_vpnipsec_manualkeylist":            dataSourceVpnIpsecManualkeyList(),
		"fortios_vpnipsec_manualkey_interface":      dataSourceVpnIpsecManualkeyInterface(),
		"fortios_vpnipsec_manualkey_interfacelist":  dataSourceVpnIpsecManualkeyInterfaceList(),
		"fortios_vpnipsec_phase1":                   dataSourceVpnIpsecPhase1(),
		"fortios_vpnipsec_phase1list":               dataSourceVpnIpsecPhase1List(),
		"fortios_vpnipsec_phase1_interface":         dataSourceVpnIpsecPhase1Interface(),
		"fortios_vpnipsec_phase1_interfacelist":     dataSourceVpnIpsecPhase1InterfaceList(),
		"fortios_vpnipsec_phase2":                   dataSourceVpnIpsecPhase2(),
		"fortios_vpnipsec_phase2list":               dataSourceVpnIpsecPhase2List(),
		"fortios_vpnipsec_phase2_interface":         dataSourceVpnIpsecPhase2Interface(),
		"fortios_vpnipsec_phase2_interfacelist":     dataSourceVpnIpsecPhase2InterfaceList(),
		"fortios_vpnsslweb_host_check_software":     dataSourceVpnSslWebHostCheckSoftware(),
		"fortios_vpnsslweb_host_check_softwarelist": dataSourceVpnSslWebHostCheckSoftwareList(),
		"fortios_vpnsslweb_portal":                  dataSourceVpnSslWebPortal(),
		"fortios_vpnsslweb_portallist":              dataSourceVpnSslWebPortalList(),
		"fortios_vpnsslweb_realm":                   dataSourceVpnSslWebRealm(),
		"fortios_vpnsslweb_realmlist":               dataSourceVpnSslWebRealmList(),
		"fortios_vpnsslweb_user_bookmark":           dataSourceVpnSslWebUserBookmark(),
		"fortios_vpnsslweb_user_bookmarklist":       dataSourceVpnSslWebUserBookmarkList(),
		"fortios_vpnsslweb_user_group_bookmark":     dataSourceVpnSslWebUserGroupBookmark(),
		"fortios_vpnsslweb_user_group_bookmarklist": dataSourceVpnSslWebUserGroupBookmarkList(),
		"fortios_vpnssl_client":                     dataSourceVpnSslClient(),
		"fortios_vpnssl_clientlist":                 dataSourceVpnSslClientList(),
		"fortios_vpnssl_settings":                   dataSourceVpnSslSettings(),

		"fortios_vpnssl_settings_authentication_rule":     dataSourceVpnSslSettingsAuthenticationRule(),
		"fortios_vpnssl_settings_authentication_rulelist": dataSourceVpnSslSettingsAuthenticationRuleList(),
		"fortios_vpn_l2tp": dataSourceVpnL2tp(),

		"fortios_vpn_ocvpn": dataSourceVpnOcvpn(),

		"fortios_vpn_pptp": dataSourceVpnPptp(),

		"fortios_waf_main_class":        dataSourceWafMainClass(),
		"fortios_waf_main_classlist":    dataSourceWafMainClassList(),
		"fortios_waf_profile":           dataSourceWafProfile(),
		"fortios_waf_profilelist":       dataSourceWafProfileList(),
		"fortios_waf_signature":         dataSourceWafSignature(),
		"fortios_waf_signaturelist":     dataSourceWafSignatureList(),
		"fortios_wanopt_auth_group":     dataSourceWanoptAuthGroup(),
		"fortios_wanopt_auth_grouplist": dataSourceWanoptAuthGroupList(),
		"fortios_wanopt_cache_service":  dataSourceWanoptCacheService(),

		"fortios_wanopt_content_delivery_network_rule":     dataSourceWanoptContentDeliveryNetworkRule(),
		"fortios_wanopt_content_delivery_network_rulelist": dataSourceWanoptContentDeliveryNetworkRuleList(),
		"fortios_wanopt_peer":                              dataSourceWanoptPeer(),
		"fortios_wanopt_peerlist":                          dataSourceWanoptPeerList(),
		"fortios_wanopt_profile":                           dataSourceWanoptProfile(),
		"fortios_wanopt_profilelist":                       dataSourceWanoptProfileList(),
		"fortios_wanopt_remote_storage":                    dataSourceWanoptRemoteStorage(),

		"fortios_wanopt_settings": dataSourceWanoptSettings(),

		"fortios_wanopt_webcache": dataSourceWanoptWebcache(),

		"fortios_web_proxy_debug_url":     dataSourceWebProxyDebugUrl(),
		"fortios_web_proxy_debug_urllist": dataSourceWebProxyDebugUrlList(),
		"fortios_web_proxy_explicit":      dataSourceWebProxyExplicit(),

		"fortios_web_proxy_forward_server":           dataSourceWebProxyForwardServer(),
		"fortios_web_proxy_forward_serverlist":       dataSourceWebProxyForwardServerList(),
		"fortios_web_proxy_forward_server_group":     dataSourceWebProxyForwardServerGroup(),
		"fortios_web_proxy_forward_server_grouplist": dataSourceWebProxyForwardServerGroupList(),
		"fortios_web_proxy_global":                   dataSourceWebProxyGlobal(),

		"fortios_web_proxy_profile":            dataSourceWebProxyProfile(),
		"fortios_web_proxy_profilelist":        dataSourceWebProxyProfileList(),
		"fortios_web_proxy_url_match":          dataSourceWebProxyUrlMatch(),
		"fortios_web_proxy_url_matchlist":      dataSourceWebProxyUrlMatchList(),
		"fortios_web_proxy_wisp":               dataSourceWebProxyWisp(),
		"fortios_web_proxy_wisplist":           dataSourceWebProxyWispList(),
		"fortios_webfilter_content":            dataSourceWebfilterContent(),
		"fortios_webfilter_contentlist":        dataSourceWebfilterContentList(),
		"fortios_webfilter_content_header":     dataSourceWebfilterContentHeader(),
		"fortios_webfilter_content_headerlist": dataSourceWebfilterContentHeaderList(),
		"fortios_webfilter_fortiguard":         dataSourceWebfilterFortiguard(),

		"fortios_webfilter_ftgd_local_cat":              dataSourceWebfilterFtgdLocalCat(),
		"fortios_webfilter_ftgd_local_catlist":          dataSourceWebfilterFtgdLocalCatList(),
		"fortios_webfilter_ftgd_local_rating":           dataSourceWebfilterFtgdLocalRating(),
		"fortios_webfilter_ftgd_local_ratinglist":       dataSourceWebfilterFtgdLocalRatingList(),
		"fortios_webfilter_ips_urlfilter_cache_setting": dataSourceWebfilterIpsUrlfilterCacheSetting(),

		"fortios_webfilter_ips_urlfilter_setting": dataSourceWebfilterIpsUrlfilterSetting(),

		"fortios_webfilter_ips_urlfilter_setting6": dataSourceWebfilterIpsUrlfilterSetting6(),

		"fortios_webfilter_override":                                         dataSourceWebfilterOverride(),
		"fortios_webfilter_overridelist":                                     dataSourceWebfilterOverrideList(),
		"fortios_webfilter_profile":                                          dataSourceWebfilterProfile(),
		"fortios_webfilter_profilelist":                                      dataSourceWebfilterProfileList(),
		"fortios_webfilter_search_engine":                                    dataSourceWebfilterSearchEngine(),
		"fortios_webfilter_search_enginelist":                                dataSourceWebfilterSearchEngineList(),
		"fortios_webfilter_urlfilter":                                        dataSourceWebfilterUrlfilter(),
		"fortios_webfilter_urlfilterlist":                                    dataSourceWebfilterUrlfilterList(),
		"fortios_wireless_controllerhotspot20_anqp_3gpp_cellular":            dataSourceWirelessControllerHotspot20Anqp3gppCellular(),
		"fortios_wireless_controllerhotspot20_anqp_3gpp_cellularlist":        dataSourceWirelessControllerHotspot20Anqp3gppCellularList(),
		"fortios_wireless_controllerhotspot20_anqp_ip_address_type":          dataSourceWirelessControllerHotspot20AnqpIpAddressType(),
		"fortios_wireless_controllerhotspot20_anqp_ip_address_typelist":      dataSourceWirelessControllerHotspot20AnqpIpAddressTypeList(),
		"fortios_wireless_controllerhotspot20_anqp_nai_realm":                dataSourceWirelessControllerHotspot20AnqpNaiRealm(),
		"fortios_wireless_controllerhotspot20_anqp_nai_realmlist":            dataSourceWirelessControllerHotspot20AnqpNaiRealmList(),
		"fortios_wireless_controllerhotspot20_anqp_network_auth_type":        dataSourceWirelessControllerHotspot20AnqpNetworkAuthType(),
		"fortios_wireless_controllerhotspot20_anqp_network_auth_typelist":    dataSourceWirelessControllerHotspot20AnqpNetworkAuthTypeList(),
		"fortios_wireless_controllerhotspot20_anqp_roaming_consortium":       dataSourceWirelessControllerHotspot20AnqpRoamingConsortium(),
		"fortios_wireless_controllerhotspot20_anqp_roaming_consortiumlist":   dataSourceWirelessControllerHotspot20AnqpRoamingConsortiumList(),
		"fortios_wireless_controllerhotspot20_anqp_venue_name":               dataSourceWirelessControllerHotspot20AnqpVenueName(),
		"fortios_wireless_controllerhotspot20_anqp_venue_namelist":           dataSourceWirelessControllerHotspot20AnqpVenueNameList(),
		"fortios_wireless_controllerhotspot20_anqp_venue_url":                dataSourceWirelessControllerHotspot20AnqpVenueUrl(),
		"fortios_wireless_controllerhotspot20_anqp_venue_urllist":            dataSourceWirelessControllerHotspot20AnqpVenueUrlList(),
		"fortios_wireless_controllerhotspot20_h2qp_advice_of_charge":         dataSourceWirelessControllerHotspot20H2qpAdviceOfCharge(),
		"fortios_wireless_controllerhotspot20_h2qp_advice_of_chargelist":     dataSourceWirelessControllerHotspot20H2qpAdviceOfChargeList(),
		"fortios_wireless_controllerhotspot20_h2qp_conn_capability":          dataSourceWirelessControllerHotspot20H2qpConnCapability(),
		"fortios_wireless_controllerhotspot20_h2qp_conn_capabilitylist":      dataSourceWirelessControllerHotspot20H2qpConnCapabilityList(),
		"fortios_wireless_controllerhotspot20_h2qp_operator_name":            dataSourceWirelessControllerHotspot20H2qpOperatorName(),
		"fortios_wireless_controllerhotspot20_h2qp_operator_namelist":        dataSourceWirelessControllerHotspot20H2qpOperatorNameList(),
		"fortios_wireless_controllerhotspot20_h2qp_osu_provider":             dataSourceWirelessControllerHotspot20H2qpOsuProvider(),
		"fortios_wireless_controllerhotspot20_h2qp_osu_providerlist":         dataSourceWirelessControllerHotspot20H2qpOsuProviderList(),
		"fortios_wireless_controllerhotspot20_h2qp_osu_provider_nai":         dataSourceWirelessControllerHotspot20H2qpOsuProviderNai(),
		"fortios_wireless_controllerhotspot20_h2qp_osu_provider_nailist":     dataSourceWirelessControllerHotspot20H2qpOsuProviderNaiList(),
		"fortios_wireless_controllerhotspot20_h2qp_terms_and_conditions":     dataSourceWirelessControllerHotspot20H2qpTermsAndConditions(),
		"fortios_wireless_controllerhotspot20_h2qp_terms_and_conditionslist": dataSourceWirelessControllerHotspot20H2qpTermsAndConditionsList(),
		"fortios_wireless_controllerhotspot20_h2qp_wan_metric":               dataSourceWirelessControllerHotspot20H2qpWanMetric(),
		"fortios_wireless_controllerhotspot20_h2qp_wan_metriclist":           dataSourceWirelessControllerHotspot20H2qpWanMetricList(),
		"fortios_wireless_controllerhotspot20_hs_profile":                    dataSourceWirelessControllerHotspot20HsProfile(),
		"fortios_wireless_controllerhotspot20_hs_profilelist":                dataSourceWirelessControllerHotspot20HsProfileList(),
		"fortios_wireless_controllerhotspot20_icon":                          dataSourceWirelessControllerHotspot20Icon(),
		"fortios_wireless_controllerhotspot20_iconlist":                      dataSourceWirelessControllerHotspot20IconList(),
		"fortios_wireless_controllerhotspot20_qos_map":                       dataSourceWirelessControllerHotspot20QosMap(),
		"fortios_wireless_controllerhotspot20_qos_maplist":                   dataSourceWirelessControllerHotspot20QosMapList(),
		"fortios_wireless_controller_access_control_list":                    dataSourceWirelessControllerAccessControlList(),
		"fortios_wireless_controller_access_control_listlist":                dataSourceWirelessControllerAccessControlListList(),
		"fortios_wireless_controller_address":                                dataSourceWirelessControllerAddress(),
		"fortios_wireless_controller_addresslist":                            dataSourceWirelessControllerAddressList(),
		"fortios_wireless_controller_addrgrp":                                dataSourceWirelessControllerAddrgrp(),
		"fortios_wireless_controller_addrgrplist":                            dataSourceWirelessControllerAddrgrpList(),
		"fortios_wireless_controller_ap_status":                              dataSourceWirelessControllerApStatus(),
		"fortios_wireless_controller_ap_statuslist":                          dataSourceWirelessControllerApStatusList(),
		"fortios_wireless_controller_apcfg_profile":                          dataSourceWirelessControllerApcfgProfile(),
		"fortios_wireless_controller_apcfg_profilelist":                      dataSourceWirelessControllerApcfgProfileList(),
		"fortios_wireless_controller_arrp_profile":                           dataSourceWirelessControllerArrpProfile(),
		"fortios_wireless_controller_arrp_profilelist":                       dataSourceWirelessControllerArrpProfileList(),
		"fortios_wireless_controller_ble_profile":                            dataSourceWirelessControllerBleProfile(),
		"fortios_wireless_controller_ble_profilelist":                        dataSourceWirelessControllerBleProfileList(),
		"fortios_wireless_controller_bonjour_profile":                        dataSourceWirelessControllerBonjourProfile(),
		"fortios_wireless_controller_bonjour_profilelist":                    dataSourceWirelessControllerBonjourProfileList(),
		"fortios_wireless_controller_global":                                 dataSourceWirelessControllerGlobal(),

		"fortios_wireless_controller_inter_controller": dataSourceWirelessControllerInterController(),

		"fortios_wireless_controller_log": dataSourceWirelessControllerLog(),

		"fortios_wireless_controller_mpsk_profile":     dataSourceWirelessControllerMpskProfile(),
		"fortios_wireless_controller_mpsk_profilelist": dataSourceWirelessControllerMpskProfileList(),
		"fortios_wireless_controller_nac_profile":      dataSourceWirelessControllerNacProfile(),
		"fortios_wireless_controller_nac_profilelist":  dataSourceWirelessControllerNacProfileList(),
		"fortios_wireless_controller_qos_profile":      dataSourceWirelessControllerQosProfile(),
		"fortios_wireless_controller_qos_profilelist":  dataSourceWirelessControllerQosProfileList(),
		"fortios_wireless_controller_region":           dataSourceWirelessControllerRegion(),
		"fortios_wireless_controller_regionlist":       dataSourceWirelessControllerRegionList(),
		"fortios_wireless_controller_setting":          dataSourceWirelessControllerSetting(),

		"fortios_wireless_controller_snmp": dataSourceWirelessControllerSnmp(),

		"fortios_wireless_controller_ssid_policy":        dataSourceWirelessControllerSsidPolicy(),
		"fortios_wireless_controller_ssid_policylist":    dataSourceWirelessControllerSsidPolicyList(),
		"fortios_wireless_controller_syslog_profile":     dataSourceWirelessControllerSyslogProfile(),
		"fortios_wireless_controller_syslog_profilelist": dataSourceWirelessControllerSyslogProfileList(),
		"fortios_wireless_controller_timers":             dataSourceWirelessControllerTimers(),

		"fortios_wireless_controller_utm_profile":      dataSourceWirelessControllerUtmProfile(),
		"fortios_wireless_controller_utm_profilelist":  dataSourceWirelessControllerUtmProfileList(),
		"fortios_wireless_controller_vap":              dataSourceWirelessControllerVap(),
		"fortios_wireless_controller_vaplist":          dataSourceWirelessControllerVapList(),
		"fortios_wireless_controller_vap_group":        dataSourceWirelessControllerVapGroup(),
		"fortios_wireless_controller_vap_grouplist":    dataSourceWirelessControllerVapGroupList(),
		"fortios_wireless_controller_wag_profile":      dataSourceWirelessControllerWagProfile(),
		"fortios_wireless_controller_wag_profilelist":  dataSourceWirelessControllerWagProfileList(),
		"fortios_wireless_controller_wids_profile":     dataSourceWirelessControllerWidsProfile(),
		"fortios_wireless_controller_wids_profilelist": dataSourceWirelessControllerWidsProfileList(),
		"fortios_wireless_controller_wtp":              dataSourceWirelessControllerWtp(),
		"fortios_wireless_controller_wtplist":          dataSourceWirelessControllerWtpList(),
		"fortios_wireless_controller_wtp_group":        dataSourceWirelessControllerWtpGroup(),
		"fortios_wireless_controller_wtp_grouplist":    dataSourceWirelessControllerWtpGroupList(),
		"fortios_wireless_controller_wtp_profile":      dataSourceWirelessControllerWtpProfile(),
		"fortios_wireless_controller_wtp_profilelist":  dataSourceWirelessControllerWtpProfileList(),
	}
}
